#server:
#  port: 8083
#
#spring:
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:testdb
#
#keycloak:
#  server:
#    contextPath: /auth
#    adminUser:
#      username: admin
#      password: test
#    realmImportFile: feign-realm.json
#
