server:
  servlet:
    context-path: /OAuthLoginDemo
    session:
        cookie:
          name: UISESSION
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: b1382016f5cfe7baf8a7
            client-secret: 3e238691e350d2fc4f61cb6105c6acc382fe1190
          facebook:
            client-id: 827574691101430
            client-secret: 3ad621e71ecd0d0771aa81e21e668732
          google:
            client-id: 800107701071-6ajh5sln3vk7pgo42bsbetuhtdefbp3m.apps.googleusercontent.com
            client-secret: s6e-rR-BxL3HBCRSeBbbNk5d

