server:
  servlet:
    context-path: /OAuthDemo
    session:
        cookie:
          name: UISESSION
  port: 8080

security:
  oauth2:
    client:
      clientId: 03afe7601faad4de2bad
      clientSecret: 6e1c4e9f5ad6f7d2b2538084b66bef793908b246
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
    sso:
      login-path: /login/github

#http://github.com/login/oauth/authorize
#?client_id=03afe7601faad4de2bad&redirect_uri=http://localhost:8080/OAuthDemo/login&response_type=code&state=5FP7I5
